amazonProperties:
   accessKey: AKIAUWJTDERIVYFIUW7C
   secretKey: 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
spring:
  application:
    name: notifier-webapp

email:
  region: us-east-1
  sender: sridharprasad.p@gmail.com